### ISSUE TITLE
Add GitHub Action for Gradle OWASP Report

### ISSUE THREAD

**Issue by craftmaster2190** [craftmaster2190/fgc#47]
https://plugins.gradle.org/plugin/org.owasp.dependencycheck

**Comment by javajoe1** [comment]
I added the plugin and tied it to the "check" step, so the github action should just pick it up. I did not configure it to fail the build. In the "dependencyCheck" section of the build.gradle file and configuration at https://jeremylong.github.io/DependencyCheck/dependency-check-gradle/configuration.html
